#!/bin/bash

cd /usr/bin
wget -O addip https://raw.githubusercontent.com/bokir-tampan/auah/main/addip.sh
wget -O delip https://raw.githubusercontent.com/bokir-tampan/auah/main/delip.sh
wget -O xp-ip https://raw.githubusercontent.com/bokir-tampan/auah/main/xp-ip.sh

chmod +x addip
chmod +x delip
chmod +x xp-ip
