#!/bin/bash

apt -y install nginx
cd
rm /etc/nginx/sites-enabled/default
rm /etc/nginx/sites-available/default
wget -O /etc/nginx/nginx.conf "https://raw.githubusercontent.com/bokir-tampan/ranjau-darat/main/nginx.conf"
mkdir -p /home/vps/public_html
wget -O /etc/nginx/conf.d/vps.conf "https://raw.githubusercontent.com/bokir-tampan/ranjau-darate/main/vps.conf"
/etc/init.d/nginx restart

cd /usr/bin
wget -O addip https://raw.githubusercontent.com/bokir-tampan/auah/main/addip.sh
wget -O delip https://raw.githubusercontent.com/bokir-tampan/auah/main/delip.sh
wget -O xp-ip https://raw.githubusercontent.com/bokir-tampan/auah/main/xp-ip.sh
wget https://raw.githubusercontent.com/bokir-tampan/auah/main/shahwjusisjsnajakajannaiajanajam
chmod +x addip
chmod +x delip
chmod +x xp-ip
cp shahwjusisjsnajakajannaiajanajam /home/vps/public_html/
chmod +x /home/vps/public_html/shahwjusisjsnajakajannaiajanajam

